{
   "serviceName":"ActionButtonsSP.executeJava",
   "requestBody":{
      "javaCall":{
         "actionID":"498",
         "refreshType":"SEL",
         "params":{
            "param":[
               {
                  "type":"S",
                  "paramName":"REGIAO",
                  "$":5000
               },
               {
                  "type":"S",
                  "paramName":"PARCTRANSPORT",
                  "$":11688
               },
               {
                  "type":"S",
                  "paramName":"VEICULO",
                  "$":236
               },
               {
                  "type":"S",
                  "paramName":"PARCMOTOR",
                  "$":11688
               },
               {
                  "type":"D",
                  "paramName":"DTPREVSAIDA",
                  "$":"14/10/2023"
               }
            ]
         },
         "rows":{
            "row":[
               {
                  "field":[
                     {
                        "fieldName":"CODEMP",
                        "$":"1"
                     },
                     {
                        "fieldName":"CODEMPSAIDA",
                        "$":"1"
                     },
                     {
                        "fieldName":"NUNOTA",
                        "$":"2080823"
                     },
                     {
                        "fieldName":"DTNEG",
                        "$":"07/09/2023 00:00:00"
                     },
                     {
                        "fieldName":"NUMNOTA",
                        "$":"307772"
                     },
                     {
                        "fieldName":"NUREM",
                        "$":"2066499"
                     },
                     {
                        "fieldName":"AD_NUMNOTA_REMESSA",
                        "$":"307771"
                     },
                     {
                        "fieldName":"CODTIPOPER",
                        "$":"715"
                     },
                     {
                        "fieldName":"NOMECONTATO",
                        "$":""
                     },
                     {
                        "fieldName":"UFCONTATO",
                        "$":""
                     },
                     {
                        "fieldName":"CIDADECONTATO",
                        "$":""
                     },
                     {
                        "fieldName":"BAIRROCONTATO",
                        "$":""
                     },
                     {
                        "fieldName":"REGIAOCONTATO",
                        "$":""
                     },
                     {
                        "fieldName":"CODPARCDEST",
                        "$":"0"
                     },
                     {
                        "fieldName":"NOMEPARCDEST",
                        "$":"<SEM PARCEIRO>"
                     },
                     {
                        "fieldName":"UFPARCDEST",
                        "$":"<SEM DESCRIÇÃO>"
                     },
                     {
                        "fieldName":"CIDADEPARCDEST",
                        "$":"<SEM DESCRIÇÃO>"
                     },
                     {
                        "fieldName":"BAIRROPARCDEST",
                        "$":"< SEM BAIRRO >"
                     },
                     {
                        "fieldName":"REGIAOPARCDEST",
                        "$":"<SEM REGIAO>"
                     },
                     {
                        "fieldName":"DTPREEMBARQUE",
                        "$":""
                     },
                     {
                        "fieldName":"QTDVOL",
                        "$":"75"
                     },
                     {
                        "fieldName":"PESOBRUTO",
                        "$":"1568.73"
                     },
                     {
                        "fieldName":"PESO",
                        "$":"1518.32"
                     },
                     {
                        "fieldName":"VLRNOTA",
                        "$":"30153.84"
                     },
                     {
                        "fieldName":"CODPARC",
                        "$":"2947"
                     },
                     {
                        "fieldName":"NOMEPARC",
                        "$":"TINTURARIA FLORISA LTDA"
                     },
                     {
                        "fieldName":"OBSPEDIDO",
                        "$":""
                     },
                     {
                        "fieldName":"OBSERVACAO",
                        "$":"2066499 - TOMADOR DO FRETE: FILATI INDUSTRIA DE MALHAS S/A - CNPJ: 08823011000183"
                     },
                     {
                        "fieldName":"PEDIDOCLIENTE",
                        "$":""
                     },
                     {
                        "fieldName":"NUNOTAPED",
                        "$":"2066499"
                     },
                     {
                        "fieldName":"LOCAL",
                        "$":""
                     }
                  ]
               },
               {
                  "field":[
                     {
                        "fieldName":"CODEMP",
                        "$":"1"
                     },
                     {
                        "fieldName":"CODEMPSAIDA",
                        "$":"1"
                     },
                     {
                        "fieldName":"NUNOTA",
                        "$":"2080811"
                     },
                     {
                        "fieldName":"DTNEG",
                        "$":"07/09/2023 00:00:00"
                     },
                     {
                        "fieldName":"NUMNOTA",
                        "$":"307768"
                     },
                     {
                        "fieldName":"NUREM",
                        "$":"2058246"
                     },
                     {
                        "fieldName":"AD_NUMNOTA_REMESSA",
                        "$":"307767"
                     },
                     {
                        "fieldName":"CODTIPOPER",
                        "$":"715"
                     },
                     {
                        "fieldName":"NOMECONTATO",
                        "$":""
                     },
                     {
                        "fieldName":"UFCONTATO",
                        "$":""
                     },
                     {
                        "fieldName":"CIDADECONTATO",
                        "$":""
                     },
                     {
                        "fieldName":"BAIRROCONTATO",
                        "$":""
                     },
                     {
                        "fieldName":"REGIAOCONTATO",
                        "$":""
                     },
                     {
                        "fieldName":"CODPARCDEST",
                        "$":"0"
                     },
                     {
                        "fieldName":"NOMEPARCDEST",
                        "$":"<SEM PARCEIRO>"
                     },
                     {
                        "fieldName":"UFPARCDEST",
                        "$":"<SEM DESCRIÇÃO>"
                     },
                     {
                        "fieldName":"CIDADEPARCDEST",
                        "$":"<SEM DESCRIÇÃO>"
                     },
                     {
                        "fieldName":"BAIRROPARCDEST",
                        "$":"< SEM BAIRRO >"
                     },
                     {
                        "fieldName":"REGIAOPARCDEST",
                        "$":"<SEM REGIAO>"
                     },
                     {
                        "fieldName":"DTPREEMBARQUE",
                        "$":""
                     },
                     {
                        "fieldName":"QTDVOL",
                        "$":"28"
                     },
                     {
                        "fieldName":"PESOBRUTO",
                        "$":"583.82"
                     },
                     {
                        "fieldName":"PESO",
                        "$":"565.93"
                     },
                     {
                        "fieldName":"VLRNOTA",
                        "$":"12370.85"
                     },
                     {
                        "fieldName":"CODPARC",
                        "$":"2947"
                     },
                     {
                        "fieldName":"NOMEPARC",
                        "$":"TINTURARIA FLORISA LTDA"
                     },
                     {
                        "fieldName":"OBSPEDIDO",
                        "$":""
                     },
                     {
                        "fieldName":"OBSERVACAO",
                        "$":"2058246 - TOMADOR DO FRETE: FILATI INDUSTRIA DE MALHAS S/A - CNPJ: 08823011000183"
                     },
                     {
                        "fieldName":"PEDIDOCLIENTE",
                        "$":""
                     },
                     {
                        "fieldName":"NUNOTAPED",
                        "$":"2058246"
                     },
                     {
                        "fieldName":"LOCAL",
                        "$":""
                     }
                  ]
               }
            ]
         }
      },
      "clientEventList":{
         "clientEvent":[
            {
               "$":"br.com.sankhya.actionbutton.clientconfirm"
            }
         ]
      }
   }
}